# Generated by Django 4.0.4 on 2022-12-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='n1_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Role', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='n2_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Credit', models.CharField(max_length=16)),
                ('Phone', models.CharField(max_length=11)),
                ('User_ID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='n3_Airline_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Country_ID', models.IntegerField(default=0)),
                ('User_ID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='n4_Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('User_ID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='n5_User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n6_Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n7_Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_ID', models.IntegerField(default=0)),
                ('Origin_ID', models.IntegerField(default=0)),
                ('Dest_ID', models.IntegerField(default=0)),
                ('Begin', models.DateTimeField()),
                ('End', models.DateTimeField()),
                ('Q_Tickets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='n8_Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flight_ID', models.IntegerField(default=0)),
                ('Cust_ID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
