# Generated by Django 4.0.4 on 2023-04-14 09:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='n1_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n2_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=11)),
                ('Credit', models.CharField(max_length=16)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n1_users')),
            ],
        ),
        migrations.CreateModel(
            name='n3_Airline_Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n5_User_Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n6_Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='n7_Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Begin_DateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('End_DateTime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Q_Tickets', models.IntegerField(default=0)),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n3_airline_companies')),
                ('Dest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dest_Countries', to='App_A.n6_countries')),
                ('Origin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Origin_Countries', to='App_A.n6_countries')),
            ],
        ),
        migrations.CreateModel(
            name='n8_Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n2_customers')),
                ('Flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n7_flights')),
            ],
        ),
        migrations.CreateModel(
            name='n4_Administrators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n1_users')),
            ],
        ),
        migrations.AddField(
            model_name='n3_airline_companies',
            name='Country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n6_countries'),
        ),
        migrations.AddField(
            model_name='n3_airline_companies',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n1_users'),
        ),
        migrations.AddField(
            model_name='n1_users',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_A.n5_user_roles'),
        ),
    ]
