# Generated by Django 4.0.4 on 2023-04-14 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_A', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='n2_customers',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='n3_airline_companies',
            old_name='Country_id',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='n3_airline_companies',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='n4_administrators',
            old_name='User_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='n7_flights',
            old_name='Company_id',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='n7_flights',
            old_name='Dest_id',
            new_name='Dest',
        ),
        migrations.RenameField(
            model_name='n7_flights',
            old_name='Origin_id',
            new_name='Origin',
        ),
        migrations.RenameField(
            model_name='n8_tickets',
            old_name='Cust_id',
            new_name='Cust',
        ),
        migrations.RenameField(
            model_name='n8_tickets',
            old_name='Flight_id',
            new_name='Flight',
        ),
    ]
