# Generated by Django 4.1.4 on 2023-04-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_A', '0002_rename_user_id_n2_customers_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n1_users',
            name='Role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='App_A.n5_user_roles'),
        ),
    ]
